// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJp_DD3D0dL09gHP-dte5d1QzJAxhv1U',
    appId: '1:999901849428:web:d09caece8dd662482f0ac1',
    messagingSenderId: '999901849428',
    projectId: 'getx-login-e8bd5',
    authDomain: 'getx-login-e8bd5.firebaseapp.com',
    storageBucket: 'getx-login-e8bd5.appspot.com',
    measurementId: 'G-PWENLMWMPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8jK5aH3fKNDZv_wJosGIW1s_ew6tLtw',
    appId: '1:999901849428:android:3c5059cc69c1be8d2f0ac1',
    messagingSenderId: '999901849428',
    projectId: 'getx-login-e8bd5',
    storageBucket: 'getx-login-e8bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2cPOkI429YKVRpiHQPvEAHwMkTIM76c',
    appId: '1:999901849428:ios:7b7151f82f977a5d2f0ac1',
    messagingSenderId: '999901849428',
    projectId: 'getx-login-e8bd5',
    storageBucket: 'getx-login-e8bd5.appspot.com',
    iosBundleId: 'com.example.flutterGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2cPOkI429YKVRpiHQPvEAHwMkTIM76c',
    appId: '1:999901849428:ios:7b76a63e329939272f0ac1',
    messagingSenderId: '999901849428',
    projectId: 'getx-login-e8bd5',
    storageBucket: 'getx-login-e8bd5.appspot.com',
    iosBundleId: 'com.example.flutterGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJp_DD3D0dL09gHP-dte5d1QzJAxhv1U',
    appId: '1:999901849428:web:77e43e6291b639f72f0ac1',
    messagingSenderId: '999901849428',
    projectId: 'getx-login-e8bd5',
    authDomain: 'getx-login-e8bd5.firebaseapp.com',
    storageBucket: 'getx-login-e8bd5.appspot.com',
    measurementId: 'G-CDY9RZP9VH',
  );
}